language: csharp
solution: ls2ovr-cs.sln
dist: xenial

matrix:
  include:
  - mono: latest
    script:
    - msbuild /p:Configuration=Release ls2ovr-cs.sln
  - dotnet: 2.2.203
    mono: none
    script:
    - dotnet build -c Release ls2ovr-cs.sln
  allow_failures:
  - mono: latest
    script:
    - msbuild /p:Configuration=Release ls2ovr-cs.sln
