language: csharp
solution: ls2ovr-cs.sln
dist: xenial

matrix:
  include:
  - &monobuild
    mono: latest
    script:
    - msbuild /p:Configuration=Release ls2ovr-cs.sln
  - dotnet: 2.2.203
    mono: none
    script:
    - dotnet build -c Release -f netstandard2.0 LS2OVR
    - dotnet build -c Release -f netcoreapp2.0 LS2OVR.Pack
    - dotnet build -c Release -f netcoreapp2.0 LS2OVR.Unpack
    - dotnet build -c Release -f netcoreapp2.0 LS2OVR.Inspect
  allow_failures:
  - *monobuild
