name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: dotnet build -c Release ls2ovr-cs.sln
    - name: Publish
      run: dotnet publish -c Release -o installdir 
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LS2OR-${{ matrix.os }}
        path: installdir
